# Generated by Django 5.1.2 on 2024-10-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_user_yandex_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='password'),
        ),
    ]
